name: flutter_app
description: 创建基础组件_新项目可直接使用

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: ^3.0.9
  connectivity: ^0.4.8+1
  shared_preferences: 0.5.7
  provider: ^4.0.4
  fluttertoast: ^3.1.0
  permission_handler: ^3.0.0
  path_provider: ^1.6.0
  sqflite: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/font/
    - assets/gif/
    - assets/json/net_response/

  fonts:
    - family: puhui_light
      fonts:
        - asset: assets/font/ali_puhui/Alibaba-PuHuiTi-Light.ttf
    - family: puhui_regular
      fonts:
        - asset: assets/font/ali_puhui/Alibaba-PuHuiTi-Regular.ttf
    - family: puhui_medium
      fonts:
        - asset: assets/font/ali_puhui/Alibaba-PuHuiTi-Medium.ttf
    - family: puhui_bold
      fonts:
        - asset: assets/font/ali_puhui/Alibaba-PuHuiTi-Bold.ttf
    - family: puhui_heavy
      fonts:
        - asset: assets/font/ali_puhui/Alibaba-PuHuiTi-Heavy.ttf
